# Goal
# Stores the data for all the vehicles
# (both the ego and agent vehicles) with the policy speed included.
std_msgs/Header header
conformal_lattice_planner/TrafficSnapshot snapshot
# Leading vehicle.
conformal_lattice_planner/Vehicle leader
float64 leading_distance
# Following vehicle.
conformal_lattice_planner/Vehicle follower
float64 following_distance
---
# Result
uint8 LANE_KEEP = 0
uint8 LEFT_LANE_CHANGE = 1
uint8 RIGHT_LANE_CHANGE = 2
uint8 UNKNOWN = 3

std_msgs/Header header
bool success
# The type of action
int8 path_type
# The new desired state of the ego.
conformal_lattice_planner/Vehicle ego
---
# Feedback
# TODO: what could a meaningful feedback?
std_msgs/Header header

