# Goal
# Policys of the ego and agent vehicles
VehicleSpeed ego_policy
VehicleSpeed ego_speed

VehicleSpeed[] agent_policies
VehicleSpeed[] agent_speed
---
# Result
bool success
VehicleSpeed ego_target_speed
---
# Feedback
# TODO: what could a meaningful feedback?
float32 percent

